name: Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests py-gitea openai anthropic google-generativeai

      - name: Run Code Review
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          FULL_CONTEXT_MODEL: gpt-4o
          FULL_CONTEXT_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SINGLE_CHUNK_MODEL: gpt-4o
          SINGLE_CHUNK_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EXCLUDE: "*.yml,*.yaml"
        run: python .gitea/scripts/code_review.py

